<script setup>
import { ref } from 'vue';
import Window from './../Window.vue';

import img1 from '../../assets/projects/p-example-1.png';
import img2 from '../../assets/projects/p-example-2.png';
import img3 from '../../assets/projects/p-example-3.png';
import Carousel from '../Carousel.vue';

const props = defineProps(['id']);

const slides = [
    {
        src: img1,
        alt: 'A timeline of operations divided by staff and resources with vessel visit information',
        legend: 'Fig1 - A Vessel visit execution operation plan generated by an algorithm'
    },
    {
        src: img2,
        alt: 'A calendar view with a list of vessel visits for a certain day',
        legend: 'Fig2 - The list of vessel visits for a given day'
    },
    {
        src: img3,
        alt: 'An isometric view of a port with warehouses, cranes and docks, a vessel is moored on the first dock',
        legend: 'Fig3 - A 3d visualization of the port'
    }
];
</script>

<template>
    <Window
        :id="props.id"
        title="OpenGL 3D Renderer"
        :resizeable="true"
        :closeable="true"
        :size="{ width: 500, height: undefined }"
    >
    
    <h3>PorTiT Port Management System</h3>
    <p>A back-end and front-end SPA system to manage vessel scheduling and resource allocation, ensuring system reliability with automated end-to-end testing using Playwright.</p>
    <p>Engineered a RESTful API in C# (.NET Core), implementing a Layered Architecture to decouple complex validation logic from high-volume data access.</p>
    <p>Includes external authentication with Google and a smart Prolog scheduling system to automatically find the most optimal arrangament of vessel visits in a given day, and a dynamic 3D visualization fo the port in THREE.js with a daynight cycle and accurate representation of vessel arrivals.</p>
    <div class="status-bar">
        <p class="status-bar-field">Made using: C#, TypeScript, Prolog, Vue, MySQL, MongoDB</p>
        <p class="status-bar-field">Status: <span class="good">Finished</span></p>
    </div>

    <br>

    <Carousel width="400" :slides="slides" />

    </Window>
</template>

<style scoped>

.full-image {
    width: 400px;
    height: auto;
    display: block;
    margin-left: auto;
    margin-right: auto;
}

.good {
    color: green;
}

.legend {
    text-align: center;
    font-style: italic;
    margin-top: 8px;
}
</style>